name: test
on:
  workflow_dispatch:
    inputs:
      variable1:
        description: 'this is variable1'
        required: true
        default: 'default-variable1'
      variable2:
        description: 'this is variable2'
        required: true
        default: 'default-variable2'
      variable3:
        description: 'this is variable3'
        required: false
        default: 'default-variable3'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initial Setup
        run: myvalues.sh
