on: 
  workflow_dispatch:
    inputs:
      variable1:
        description: 'variable1-description'     
        required: true
        default: 'variable1-value'
      variable2:
        description: 'variable2-description'     
        required: true
        default: 'variable2-value'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#    - run: bash myshellscriptfile.sh
    - run: | 
        echo "variable1: ${{ github.event.inputs.variable1 }}"
        echo "variable2: ${{ github.event.inputs.variable2 }}"
